### ISSUE TITLE
Breaking recursive clone of hugoThemes

### ISSUE THREAD

**Issue by HokieTT** [nilproductions/hugo-bootswatch#1]
git clone --recursive https://github.com/spf13/hugoThemes themes
Cloning into 'themes'...

...

Cloning into 'hugo-bootswatch'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Clone of 'git@github.com:nilproductions/hugo-bootswatch.git' into submodule path 'hugo-bootswatch' failed

**Comment by anthonyfok** [comment]
I think it was a problem with `.gitmodule` in https://github.com/spf13/hugoThemes/ which has now been fixed in spf13/hugoThemes#26, so I guess this #1 may also be closed too.

**Comment by imperialwicket** [comment]
Sorry! Thanks for the fix.
