### ISSUE TITLE
Images missing max-width property

### ISSUE THREAD

**Issue by paskal** [nilproductions/hugo-bootswatch#3]
Hello!

Great theme, thanks for the effort! I've stumbled upon the very same issue as the https://github.com/dim0627/hugo_theme_beg/issues/19:
![image](https://user-images.githubusercontent.com/712534/37663888-4877b400-2c6b-11e8-8a3d-e20cb4a88a2c.png)

**Comment by imperialwicket** [comment]
Thanks, I haven't been able to keep this current with hugo's motion, but if I get time I'll add this to the clean up tasks.

Appreciate the report!
